server {
    listen 8080;
    server_name *.example.com;
    access_log /var/log/nginx/test-access.log main;
    error_log /var/log/nginx/test-error.log;

    location / {
        proxy_pass http://app01:8080;
    }
}

server {
    listen 8081;
    server_name *.example.com;
    access_log /var/log/nginx/test-access.log main;
    error_log /var/log/nginx/test-error.log;

    location / {
        proxy_pass http://app02:8080;
    }
}
