input {
  beats {
    port => 5044 
  }
}


filter {
}

output {
  if "nginx" in [tags] {
    pipeline {
      send_to => nginx_pipeline
    }
  } else {
    pipeline {
      send_to => app_pipeline
    }
  }
}