input {
  beats {
    port => 5044 
  }
}


filter {
  if "nginx" in [tags] {
    grok {
      match => {
        "message" => "%{IPORHOST:remote_addr}\s+-\s+%{USER:remote_user}\s+\[%{HTTPDATE:time_local}]\s+\"%{WORD:method}\s+%{NOTSPACE:path}\s+HTTP/%{NUMBER:httpversion}\"\s+%{NUMBER:status}\s+%{NUMBER:bytes}\s+\"%{NOTSPACE:referer}\"\s+\"%{DATA:agent}\"\s+\"%{NOTSPACE:http_x_forwarded_for}\"\s+\"service=%{DATA:service}\""
      }
    }

    date {
      match => ["time_local", "dd/MMM/yyyy:HH:mm:ss Z"]
      target => "@timestamp"
      timezone => "Asia/Tokyo"
    }

    mutate {
      remove_field => ["time_local"]
    }
  }
}

output {
  if "nginx" in [tags] {
    elasticsearch {
      index => "nginx-%{+YYYY.MM.dd}"
      hosts=> ["https://es01:9200", "https://es02:9200", "https://es03:9200"]
      user=> "${ELASTIC_USER}"
      password=> "${ELASTIC_PASSWORD}"
      cacert=> "certs/ca/ca.crt"
    }
  } else {
    elasticsearch {
      index => "app-%{+YYYY.MM.dd}"
      hosts=> ["https://es01:9200", "https://es02:9200", "https://es03:9200"]
      user=> "${ELASTIC_USER}"
      password=> "${ELASTIC_PASSWORD}"
      cacert=> "certs/ca/ca.crt"
    }
  }
}